[package]
name = "iron-gcd"
version = "0.1.0"
authors = ["raimon <raimon49@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
